version: "3"
services:

############################################################
## PostGres ################################################
############################################################

#-----------------------------------------------------------
#-- UI -----------------------------------------------------
#-----------------------------------------------------------
  # [fn_mb_cite]
  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3007:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
  # [fn_driver]
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres-db
    depends_on:
      - postgres-db
    links:
      - postgres-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 2878:8080
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      volumes:
        # [fn_owner]
        - ./data/pgadmin:/var/lib/pgadmin
      ports:
        - "5050:80"

#-----------------------------------------------------------
#-- Database -----------------------------------------------
#-----------------------------------------------------------

  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./pgdata:/var/lib/postgresql/data

############################################################
## Ollama ##################################################
############################################################

#-----------------------------------------------------------
#-- Server -------------------------------------------------
#-----------------------------------------------------------


    ollama:
        restart: unless-stopped
        image: ollama/ollama
        container_name: ollama
        ports:
            - '11434:11434'
        volumes:
            - './data:/root/.ollama'
            - './data_custom-models:/opt/custom_models'
        deploy:
            resources:
              reservations:
                devices:
                  - driver: nvidia
                    device_ids: ['0', '1']
                 #  device_ids: ['0']
                    capabilities: [gpu]


#-----------------------------------------------------------
#-- Web UI [Optional] --------------------------------------
#-----------------------------------------------------------
    open-webui:
        image: 'ghcr.io/open-webui/open-webui:main'
        restart: always
        container_name: open-webui
        volumes:
            - './data_open-webui:/app/backend/data'
        # [fn_external_ollama]
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '3000:8080'
        depends_on:
            - ollama

############################################################
## Footnotes ###############################################
############################################################

# [fn_owner]
  # Must be owned by 5050 <https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#mapped-files-and-directories>
  # chown -R 5050:5050 ./data/

# [fn_mb_cite]
  # Adapted from <https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker>

# [fn_driver]
  # Comment out all environment variables to just use H2 Driver
  # If using postgres, `CREATE DATABASE metabaseappdb` and restart container
  # on first run.

# [fn_external_ollama]
  # Uncomment this for external ollama
  #       environment:
  #           - 'OLLAMA_BASE_URL=https://example.com'
  # Comment or uncomment this for locally hosted ollama
